' ******************************************************************************
' swxJRNL.swj - journal recorded on 09/07/25 by NV
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "final assembly.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
' MSGBOX
' Warning: The file C:\Users\hp\Gripper-CAD\gripper\final assembly.SLDASM is from educational version. This file is for instructional use only.

Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01096511563302811181, 0, 0.02601679662695485784, 0.06079033327850755231, -0.0139268403262514124
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.3216433919021579602, 0.05363694774421610967, 0.02601679662695485784, 0.06079033327850755231, -0.0139268403262514124
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06579069379816866736, 0.007662421106316585732, 0.02601679662695485784, 0.06079033327850755231, -0.0139268403262514124

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.3508837002568995778, 0.2288096383539391931, 0.01789469238532708645, 0.1068915021095578066, 0.008123159673749229606
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007310077088685408737, -0.3432144575309088452, 0.01789469238532708645, 0.1068915021095578066, 0.008123159673749229606
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007626987945131307421, 0.01789469238532708645, 0.1068915021095578066, 0.008123159673749229606

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06579069379816866736, 0.1296587950672322131, -0.01800679500368573827, 0.06539081285073677918, -0.01387320143066972378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003655038544342704369, 0.05338891561591914414, -0.01800679500368573827, 0.06539081285073677918, -0.01387320143066972378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.04576192767078784279, -0.01800679500368573827, 0.06539081285073677918, -0.01387320143066972378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0381349397256565345, -0.01800679500368573827, 0.06539081285073677918, -0.01387320143066972378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0228809638353939214, -0.01800679500368573827, 0.06539081285073677918, -0.01387320143066972378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0381349397256565345, -0.01800679500368573827, 0.06539081285073677918, -0.01387320143066972378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003655038544342704369, 0.0228809638353939214, -0.01800679500368573827, 0.06539081285073677918, -0.01387320143066972378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0228809638353939214, -0.01800679500368573827, 0.06539081285073677918, -0.01387320143066972378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003655038544342704369, 0, -0.01800679500368573827, 0.06539081285073677918, -0.01387320143066972378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003655038544342704369, 0.007626987945131307421, -0.01800679500368573827, 0.06539081285073677918, -0.01387320143066972378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003655038544342704369, 0.007626987945131307421, -0.01800679500368573827, 0.06539081285073677918, -0.01387320143066972378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003655038544342704369, 0.01525397589026261484, -0.01800679500368573827, 0.06539081285073677918, -0.01387320143066972378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003655038544342704369, 0.007626987945131307421, -0.01800679500368573827, 0.06539081285073677918, -0.01387320143066972378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003655038544342704369, 0.01525397589026261484, -0.01800679500368573827, 0.06539081285073677918, -0.01387320143066972378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007626987945131307421, -0.01800679500368573827, 0.06539081285073677918, -0.01387320143066972378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007626987945131307421, -0.01800679500368573827, 0.06539081285073677918, -0.01387320143066972378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007626987945131307421, -0.01800679500368573827, 0.06539081285073677918, -0.01387320143066972378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007310077088685408737, 0.01525397589026261484, -0.01800679500368573827, 0.06539081285073677918, -0.01387320143066972378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03289534689908433368, 0.01525397589026261484, -0.01800679500368573827, 0.06539081285073677918, -0.01387320143066972378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04386046253211244722, 0.007626987945131307421, -0.01800679500368573827, 0.06539081285073677918, -0.01387320143066972378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03655038544342704282, 0, -0.01800679500368573827, 0.06539081285073677918, -0.01387320143066972378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01462015417737081747, 0, -0.01800679500368573827, 0.06539081285073677918, -0.01387320143066972378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003655038544342704369, 0, -0.01800679500368573827, 0.06539081285073677918, -0.01387320143066972378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007626987945131307421, -0.01800679500368573827, 0.06539081285073677918, -0.01387320143066972378

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
' MSGBOX
' Save changes to final assembly.SLDASM?

Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003655038544342704369, 0, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.2156472741162195339, 0.06101590356105045937, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04751550107645514942, -0.0228809638353939214, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01827519272171352141, -0.007626987945131307421, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01462015417737081747, -0.0228809638353939214, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02193023126605622361, -0.01525397589026261484, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01827519272171352141, -0.01525397589026261484, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02193023126605622361, -0.01525397589026261484, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003655038544342704369, 0, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007626987945131307421, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01096511563302811181, -0.01525397589026261484, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01827519272171352141, -0.01525397589026261484, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01096511563302811181, -0.01525397589026261484, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003655038544342704369, 0, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003655038544342704369, 0, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003655038544342704369, 0, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003655038544342704369, 0.01525397589026261484, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003655038544342704369, 0.01525397589026261484, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003655038544342704369, 0.0228809638353939214, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007626987945131307421, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007626987945131307421, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0228809638353939214, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007626987945131307421, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0381349397256565345, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007310077088685408737, 0.0381349397256565345, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01096511563302811181, 0.06101590356105045937, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01462015417737081747, 0.05338891561591914414, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01827519272171352141, 0.09152385534157568558, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02193023126605622361, 0.09915084328670699387, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02558526981039892928, 0.09152385534157568558, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02193023126605622361, 0.1296587950672322131, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03655038544342704282, 0.1449127709574948297, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03655038544342704282, 0.152539758902626138, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02193023126605622361, 0.07626987945131306901, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01827519272171352141, 0.06864289150618176072, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01462015417737081747, 0.05338891561591914414, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007310077088685408737, 0.0381349397256565345, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007310077088685408737, 0.0381349397256565345, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007310077088685408737, 0.0228809638353939214, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007310077088685408737, 0.0381349397256565345, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01096511563302811181, 0.0381349397256565345, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0228809638353939214, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003655038544342704369, 0.007626987945131307421, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003655038544342704369, 0.007626987945131307421, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01096511563302811181, 0.0228809638353939214, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007310077088685408737, 0.01525397589026261484, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007310077088685408737, 0.007626987945131307421, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003655038544342704369, 0.007626987945131307421, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007626987945131307421, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007310077088685408737, 0, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01462015417737081747, 0, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03289534689908433368, -0.01525397589026261484, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02924030835474163495, -0.0228809638353939214, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03655038544342704282, -0.0228809638353939214, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02924030835474163495, -0.0228809638353939214, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03289534689908433368, -0.0381349397256565345, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02558526981039892928, -0.0381349397256565345, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03655038544342704282, -0.06101590356105045937, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01827519272171352141, -0.03050795178052522968, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003655038544342704369, -0.01525397589026261484, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003655038544342704369, 0, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01462015417737081747, -0.04576192767078784279, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01462015417737081747, -0.0381349397256565345, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02924030835474163495, -0.09915084328670699387, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.05482557816514056076, -0.1830477106831513712, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0584806167094832699, -0.2211826504088078849, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04751550107645514942, -0.152539758902626138, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02193023126605622361, -0.09915084328670699387, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02924030835474163495, -0.1296587950672322131, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03289534689908433368, -0.1906746986282826795, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02193023126605622361, -0.1601667468477574463, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01096511563302811181, -0.1144048191769695966, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01096511563302811181, -0.0838968673964443773, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01462015417737081747, -0.09152385534157568558, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02558526981039892928, -0.1449127709574948297, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02558526981039892928, -0.1296587950672322131, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02193023126605622361, -0.0838968673964443773, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01096511563302811181, -0.0381349397256565345, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02193023126605622361, -0.04576192767078784279, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01096511563302811181, -0.01525397589026261484, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01096511563302811181, -0.007626987945131307421, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01096511563302811181, 0, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01096511563302811181, 0, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02558526981039892928, -0.007626987945131307421, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03289534689908433368, -0.007626987945131307421, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.05482557816514056076, -0.01525397589026261484, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03289534689908433368, -0.01525397589026261484, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.09868604069725300798, -0.03050795178052522968, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04386046253211244722, -0.0228809638353939214, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04386046253211244722, -0.0381349397256565345, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02193023126605622361, -0.0228809638353939214, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01827519272171352141, -0.04576192767078784279, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01827519272171352141, -0.04576192767078784279, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01462015417737081747, -0.05338891561591914414, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01096511563302811181, -0.04576192767078784279, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007310077088685408737, -0.03050795178052522968, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007626987945131307421, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007626987945131307421, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003655038544342704369, 0, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02558526981039892928, 0.03050795178052522968, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.05482557816514056076, 0.09152385534157568558, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02193023126605622361, 0.06101590356105045937, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007310077088685408737, 0.01525397589026261484, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01827519272171352141, 0.03050795178052522968, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02558526981039892928, 0.05338891561591914414, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04386046253211244722, 0.05338891561591914414, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01827519272171352141, 0.0381349397256565345, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01096511563302811181, 0.0228809638353939214, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003655038544342704369, 0, 0.02788058536754078887, 0.067233360253084129, -0.01934418998030196235

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
' MSGBOX
' Save changes to final assembly.SLDASM?

swApp.ExitApp
End Sub
